---
- name: automatic first installation
  hosts: localhost
  connection: local
  tasks:
    - name: creating jenkins usererror
      become: true
      shell: useradd jenkins
    - name: editing sudoers
      shell : sudo echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
